import Head from 'next/head';
import Image from 'next/image';

import Link from 'next/link';

export default function Home() {

  return (
    <div className='bg-[url(/img/bg.png)] bg-cover bg-center '>
      <Head>
        <title>Covid Test</title>
        <meta name="description" content="Generated by create next app" />
      </Head>


      {/* <div className='fixed w-full h-full bg-app-primary'></div> */}
      <main className="bg-white shadow-2xl backdrop-blur-2xl flex flex-col justify-center items-center relative w-full h-screen p-8 max-w-lg lg:p-20 ml-auto space-y-4 z-100 isolate">

        <div className='relative w-full h-36'>
          <Image src="/img/virus.svg" layout='fill' objectFit='contain' />
        </div>

        <p className="font-DM-Serif text-2xl text-center">Take a free COVID test</p>
        <p className='text-sm text-center'>Answer these survey questions and find out how likely you are to have contracted covid</p>

        <Link href="/instructions" className='block w-full text-center text-white font-DM-Serif !mt-8 p-3 bg-[#5025d8]'>
          Begin Test
        </Link>
        

      </main>

    </div>
  )
}
