import Head from 'next/head';
import Image from 'next/image';

import Link from 'next/link';

export default function Home() {

  return (
    <div>
      <Head>
        <title>Covid Test</title>
        <meta name="description" content="Generated by create next app" />
      </Head>


      {/* <div className='fixed w-full h-full bg-app-primary'></div> */}
      <main className="">
        <div className='flex flex-col justify-center items-center relative w-full lg:h-screen p-8 max-w-lg lg:p-20 mx-auto space-y-8 z-100 backdrop-blur-2xl isolate'>
          <div className='relative w-full h-40'>
            <Image src="/img/medical-check.svg" layout='fill' objectFit='contain' />
          </div>

          <p className="font-DM-Serif text-2xl self-start">Instruction</p>
          <p className='text-sm self-start flex gap-2'><strong>1. </strong> Do ensure you answer these questions truthfully</p>
          <p className='text-sm self-start flex gap-2'><strong>2. </strong> These survey does not represent the final outcome of your condition. Please refer to a physician even after taking this survey</p>
          <p className='text-sm self-start flex gap-2'><strong>3. </strong> This survey does not represent any advice from a medical practitioner please refer to one for better communnication about your health</p>

          <Link href="/start-assessment" className='block w-full text-center text-white font-DM-Serif !mt-8 p-3 bg-[#5025d8]'>
            Take Survey
          </Link>
        </div>

      </main>

    </div>
  )
}
